# Generated by Django 4.1.3 on 2022-12-03 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
