# Generated by Django 4.1.3 on 2022-11-12 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tipolancamentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('descricao', models.CharField(max_length=100, unique=True)),
                ('classificacao', models.CharField(choices=[('D', 'Despesa'), ('R', 'Receita')], default='D', max_length=2)),
                ('tipo', models.CharField(choices=[('CP', 'Contas a Pagar'), ('CR', 'Contas a Receber'), ('CX', 'Caixa')], max_length=2)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6)),
                ('observacoes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo_lancamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipolancamentos.tipolancamento')),
            ],
        ),
    ]
